apiVersion: gloo.solo.io/v1
kind: Upstream # Defines the resource type, which represents a backend service for routing traffic
metadata:
  labels:
    app: gloo # Label to associate this Upstream with the Gloo Gateway application
  name: gemini # Name of the Upstream resource for identification and reference
  namespace: gloo-system # Namespace where the Upstream resource is deployed
spec:
  ai:
    gemini:
      model: gemini-1.5-flash # Specifies the Google Gemini AI model being targeted
      apiVersion: v1beta # Defines the API version for interacting with the Gemini service
      authToken:
        secretRef:
          name: gemini-secret # References a Kubernetes Secret that stores the authentication token
          namespace: gloo-system # Specifies the namespace where the Secret is located