apiVersion: gateway.solo.io/v1
kind: RouteOption
metadata:
  name: gemini-route-option
  namespace: gloo-system
spec:
  targetRefs:
  - group: gateway.networking.k8s.io
    kind: HTTPRoute # Indicates that the RouteOption applies to an HTTPRoute resource
    name: gemini-route # Name of the target HTTPRoute to which this configuration will be applied
    namespace: gloo-system # Namespace of the target HTTPRoute
  options:
    rbac: # Configures role-based access control (RBAC) for this route
      policies:
        viewer:
          nestedClaimDelimiter: .
          principals: # Defines the entities allowed to access this route
          - jwtPrincipal: # Specifies that access is based on JWT claims
              claims:
                team: dev # Requires the JWT to contain the claim "team: dev" for access