apiVersion: ratelimit.solo.io/v1alpha1
kind: RateLimitConfig
metadata:
  name: per-user-counter
  namespace: gloo-system
spec:
  raw:
    descriptors:
    - key: user-id
      rateLimit:
        requestsPerUnit: 25
        unit: HOUR
    rateLimits:  # Defines the logic to extract and enforce rate limits dynamically
    - actions:
      - metadata: # Specifies how the key `user-id` is derived
          descriptorKey: user-id # Maps the metadata value to the `user-id` descriptor
          source: DYNAMIC # Indicates the metadata is dynamically extracted at runtime
          default: unknown
          metadataKey:
            key: "envoy.filters.http.jwt_authn" # Specifies the Envoy filter used to extract JWT claims
            path:
            - key: principal # Navigates through the JWT payload to locate the principal field
            - key: sub # Extracts the "sub" claim from the JWT token to identify the user